services:
 
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: swifty
      PGUSER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    build: .
    # restart: always
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app/
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: match_user
      DB_PASSWORD: swifty
      DB_NAME: match_db